# Generated by Django 3.2.7 on 2021-09-15 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('isbn13', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Libraries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.FloatField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.books')),
            ],
        ),
    ]
